# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 755e84eff1c00dca0c3391e584e542cfb1144181b5b06950bbb316660373dc2b83bbbcac0c1176799821fd51f959f9e4cce422709d43212ceaff9e5ee6e2de92

test:
  secret_key_base: e0bbc06a083077aee958dfd1c5742c9873a848491ad2384bdbdecbb7af590d4f5758255b7f431ea05a5742469496bd40d66955568f58916839c090084eb56584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
